server:
  port: 1010
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  datasource:
    username: postgres
    password: test
    url: jdbc:postgresql://localhost:6789/postgres
  application:
    name: poker-serverte
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.61:8888/eureka/

service:
  registration:
    rootPath: http://registration-service
    authPath: http://registration-service/api/user/auth
    registrationPath: http://registration-service/api/user/registration
    activationPath: http://registration-service/api/user/activation/{code}
  email:
    rootPath: http://email-service
    sendPath: http://email-service/api/mail/send
    savePath: http://email-service/api/mail/save

config:
  socket:
    poker-game-path: "/poker/game"
    ready-players-path: "/poker/game/ready/players"
    error-path: "/poker/error"
    flop-path: "/poker/game/flop"
    tern-path: "/poker/game/tern"
    river-path: "/poker/game/river"
    bank-path: "/poker/game/bank"
    games-path: "/poker/games"
  cors:
    hosts:
      - "http://127.0.0.1:8080"
    credentials: true
    methods:
      - "GET"
      - "HEAD"
      - "OPTIONS"
      - "POST"
      - "PUT"
    headers:

